### PR TITLE
Flow typings fixes #151

### LINKED ISSUE #151: Investigate Adding Flow Types

### PR DESCRIPTION
**Pull request by RiddleMan**
Hey :)
I've added flow typings based on existing branch created by @ellbee.
Unfortunately part of them are not related only to flow, but TS.
I reviewed some of them and they don't seem to break (
Most of them are formatting changes + definition for table overload)

Thank you in advance for review

@edit:
I've changed base to v3.0.0 and everything related to TS went away 👍

### CODE REVIEW

**Comment by ellbee** [comment]
Hey @RiddleMan, thanks for this. I'll give it a try tonight.

**Comment by pcardune** [comment]
Any idea when this will make it into a release?

**Comment by hmeerlo** [comment]
Ok, this seems very usefull! @ellbee  What is the PR status?

**Comment by hmeerlo** [comment]
@ellbee Any chance to see this in 2.x as well, or is 3.0.0 coming soon?

**Comment by ahutchings** [comment]
@ellbee, @RiddleMan - I have these typings ready for reselect 2.x in a branch of flow-typed here: https://github.com/ahutchings/flow-typed/tree/feature/reselect-2. Would either of you mind if I submit them to flow-typed so that reselect users can benefit from them before 3.x is released?

**Pull request merged**
