### PR TITLE
Update to Yarn 4.4.1

### PR DESCRIPTION
**Pull request by aryaemami59**
## **This PR**:

- [X] Upgrades Yarn to version 4.4.1.

### CODE REVIEW

**Comment by EskiMojo14** [comment]
this looks good, but CI is failing

**Comment by aryaemami59** [comment]
@EskiMojo14 https://github.com/reduxjs/redux-toolkit/pull/4601 needs to be merged.

**Comment by EskiMojo14** [comment]
gotcha :)

**Comment by EskiMojo14** [comment]
thanks!

**Pull request merged**
