### PR TITLE
add missing typescript typing for createSelector method with array of…

### PR DESCRIPTION
**Pull request by pyu10055**
… selectors

### CODE REVIEW

**Comment by aikoven** [comment]
Please see https://github.com/reactjs/reselect/pull/192

**Comment by pyu10055** [comment]
@aikoven the PR in #192 still does not define the method signature for array of selector AFAICT. And the conversation is quite long, can you elaborate what is the plan for supporting that? Thanks.

**Comment by aikoven** [comment]
@pyu10055 It does, see https://github.com/aikoven/reselect/blob/8c48a39b1090c7af830e3a0b59b1408198e18471/src/index.d.ts#L272-L536

Tests:
https://github.com/aikoven/reselect/blob/8c48a39b1090c7af830e3a0b59b1408198e18471/typescript_test/test.ts#L123-L262

**Comment by ellbee** [comment]
@aikoven Can this be closed?

**Comment by aikoven** [comment]
I guess so. 

@pyu10055 do you still have any concerns?

**Comment by ellbee** [comment]
I'll close this.

@pyu10055 Feel free to re-open if you think there is a still a problem.

**Pull request closed without merging**
