### PR TITLE
Check if "some" arg is not equal instead of checking if "every" arg is equal

### PR DESCRIPTION
**Pull request by dara76**
(changed the title to make it fit)

### CODE REVIEW

**Comment by ellbee** [comment]
Hey @dara76, thanks for the PR. I'm afraid I don't understand the reason for the proposed change.

**Comment by dara76** [comment]
@ellbee - My thinking is it's a small performance improvement when `args` is different to `lastArgs` because if one argument fails the equality check then there's no need to check the rest of the arguments, we already know that we will need to call the function again.

**Comment by ellbee** [comment]
`Array.every` returns false as soon as it finds an element that returns a falsy value from the predicate function, so I don't think this PR will result in a performance increase.

**Comment by ellbee** [comment]
I think that `Array.every` reads better here so I am going to close this out, but thanks for taking the time to contribute, I do appreciate it.

**Comment by dara76** [comment]
> Array.every returns false as soon as it finds an element that returns a falsy value from the predicate function

Of course it does, not sure what I was thinking.

**Pull request closed without merging**
